### ISSUE TITLE
Not working for Camera set Facing FRONT

### ISSUE THREAD

**Issue by shubh261096** [shadowsheep1/cameraxbasic-playground#1]
`private var lensFacing = CameraX.LensFacing.FRONT`

Not working if the camera facing is set to front

**Comment by shadowsheep1** [comment]
There was an issue with the 270 degrees image rotation. Now that has been solved by this https://github.com/shadowsheep1/cameraxbasic-playground/pull/2

**Comment by shadowsheep1** [comment]
@shubh261096 If you find my SO question/answer useful, please consider update them [-;

**Comment by shadowsheep1** [comment]
@shubh261096 If you find my SO question/answer useful, please consider upvote them [-;
